### ISSUE TITLE
Pic2Cam is not working on Samsung Galaxy S9 Android 10

### ISSUE THREAD

**Issue by hope-faith1** [adriangl/pict2cam#213]
I have a Samsung Galaxy S9 rooted with Magisk Canary running stock android 10. The android security patch level is "March 1, 2022."

I downloaded pic2cam and made a system app by moving in to "system-priv" and made sure it has proper permission by allowing access to "storage."

I then open my browser and went to webcamtoy.com and it doesn't prompt to choose camera or select the image for the camera. 

Its the same issue when I try it with other apps. It doesn't prompt to select camera or choose picture as camera.

In settings for the camera app I am not able to change the default camera to pic2cam as its grayed out. 

Any help is greatly appreciated! 

![Screenshot_20231007-163609_Settings](https://github.com/adriangl/pict2cam/assets/139982008/8d58500b-2ac2-48d3-a1bc-578afc67f572)

![Uploading Screenshot_20231007-165635_Settings.jpg…]()

**Comment by grigotierpascal** [comment]
Can you optain a Xiaomi ? I heard its only possible with it

**Comment by adriangl** [comment]
Hello!
Pict2Cam only works if an app that you installed in your phone requests the system camera app to take photos, so no, it won't work for your use case since webcamtoy.com is a webpage.

For the other use case, if the app you want to use doesn't require the system camera app, it won't work either, no matter if you install it as a system app or not.

Regards
