### ISSUE TITLE
App exits after selecting tick icon on credits page

### ISSUE THREAD

**Issue by harshit-hooda** [adriangl/pict2cam#62]
Hi, the app closes itself after user ticks on the tick icon on credit page. This could be a bug, please fix it. Thanks for your time.
Version: 1.0.41

**Comment by adriangl** [comment]
Hello @harshit-hooda! Sorry for the late reply.

That's in fact the expected behaviour, the app that you open from your launcher/desktop is only a tutorial: it only explains what to do to use Pict2Cam with other apps that allow it.

Maybe I should be a bit more explicit about this in the app, I'll try taking a look to it so this is clearer :D
