### ISSUE TITLE
Android 11+

### ISSUE THREAD

**Issue by Gary-0ak** [adriangl/pict2cam#63]
Any leads on a similar feature for Android 11+?

**Comment by adriangl** [comment]
I'd like to give you good news about this, but unfortunately I can't: there's no way to use this app properly in Android 11 or above because of this: https://9to5google.com/2020/08/18/android-11-default-camera-app-changes/

There might be a way to override this behaviour with a rooted phone, but I don't know if such method exists currently (as I don't have a rooted phone).

**Comment by Gary-0ak** [comment]
Acknowledged
