### ISSUE TITLE
Please provide a signed APK

### ISSUE THREAD

**Issue by IzzySoft** [adriangl/pict2cam#77]
Could you please attach a signed APK to your releases? App bundles are non-trivial for the average user – and Play Store a no-go for the privacy-focused :wink:

Speaking of the latter: Applying for inclusion at [F-Droid](https://f-droid.org/) might be a good idea :smiley:

**Comment by IzzySoft** [comment]
Ugh? Makes no sense to assign this to me, I cannot work on it :rofl:

**Comment by adriangl** [comment]
Yeah, sorry, I was testing the waters with the CI system to publish app bundles to the stores, but it's true that it doesn't make much sense to upload the AABs to releases here since you won't be able to install them by usual means. Now the releases should upload APKs instead of AABs :)

About publishing the app to F-Droid, I may take a look at it, thanks for suggesting it!

**Comment by IzzySoft** [comment]
Thanks a lot! Meanwhile, [in another universe](https://apt.izzysoft.de/fdroid/index/apk/com.adriangl.pict2cam)… As long as there's an APK attached to new tags, it will be automatically updated (usually within 24h). And if you want to link there, [here's a badge for that](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it).

Should you need help getting your app to "F-Droid proper", I'll be there (disclosure: I'm one of the maintainers).
